name: deploy
on:
  push:
    branches: [main]
env:
  SHARP_INSTALL_FORCE: true
  APP_BASE_PATH: /recodo/
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build --base=$APP_BASE_PATH
      - name: Recreate gh-pages branch
        run: git checkout -b gh-pages
      - name: Promote build
        run: mv dist /tmp/dist && ls | grep -v ".git" | xargs rm -r && mv /tmp/dist/* .
      - name: Publish build
        run: git config --global user.email "ci@github.com" && git config --global user.name "Github CI" && git add --all && git commit -m "updated build" && git push --set-upstream origin gh-pages --force
